INSERT INTO ROLES
VALUES (7,6,"Munster");
INSERT INTO ROLES
VALUES (8,4,"Nordland");
INSERT INTO ROLES
VALUES (8,3,"Molise");
INSERT INTO ROLES
VALUES (5,9,"Aisén");
INSERT INTO ROLES
VALUES (2,5,"Lubelskie");
INSERT INTO ROLES
VALUES (8,2,"Noord Holland");
INSERT INTO ROLES
VALUES (10,5,"East Kalimantan");
INSERT INTO ROLES
VALUES (1,3,"Mpumalanga");
INSERT INTO ROLES
VALUES (1,7,"Valparaíso");
INSERT INTO ROLES
VALUES (5,4,"Benue");
INSERT INTO ROLES
VALUES (10,3,"Aydın");
INSERT INTO ROLES
VALUES (3,8,"North Chungcheong");
INSERT INTO ROLES
VALUES (1,7,"Khyber Pakhtoonkhwa");
INSERT INTO ROLES
VALUES (5,2,"Gävleborgs län");
INSERT INTO ROLES
VALUES (9,7,"Corse");
INSERT INTO ROLES
VALUES (10,2,"Brussels Hoofdstedelijk Gewest");
INSERT INTO ROLES
VALUES (5,4,"Umbria");
INSERT INTO ROLES
VALUES (3,9,"Canarias");
INSERT INTO ROLES
VALUES (3,5,"Provence-Alpes-Côte d'Azur");
INSERT INTO ROLES
VALUES (9,4,"Vienna");