INSERT INTO CLIENTS
VALUES (1,8);
INSERT INTO CLIENTS
VALUES (2,3);
INSERT INTO CLIENTS
VALUES (3,3);
INSERT INTO CLIENTS
VALUES (4,9);
INSERT INTO CLIENTS
VALUES (5,6);
INSERT INTO CLIENTS
VALUES (6,8);
INSERT INTO CLIENTS
VALUES (7,3);
INSERT INTO CLIENTS
VALUES (8,1);
INSERT INTO CLIENTS
VALUES (9,9);
INSERT INTO CLIENTS
VALUES (10,9);
INSERT INTO CLIENTS
VALUES (11,1);
INSERT INTO CLIENTS
VALUES (12,0);
INSERT INTO CLIENTS
VALUES (13,5);
INSERT INTO CLIENTS
VALUES (14,1);
INSERT INTO CLIENTS
VALUES (15,0);
INSERT INTO CLIENTS
VALUES (16,8);
INSERT INTO CLIENTS
VALUES (17,6);
INSERT INTO CLIENTS
VALUES (18,2);
INSERT INTO CLIENTS
VALUES (19,6);
INSERT INTO CLIENTS
VALUES (20,7);
