PROMPT *************** INSERTION IN UTILISATEUR *****************

INSERT INTO UTILISATEUR
VALUES (1,3);
INSERT INTO UTILISATEUR
VALUES (2,9);
INSERT INTO UTILISATEUR
VALUES (3,6);
INSERT INTO UTILISATEUR
VALUES (4,4);
INSERT INTO UTILISATEUR
VALUES (5,3);
INSERT INTO UTILISATEUR
VALUES (6,8);
INSERT INTO UTILISATEUR
VALUES (7,1);
INSERT INTO UTILISATEUR
VALUES (8,6);
INSERT INTO UTILISATEUR
VALUES (9,7);
INSERT INTO UTILISATEUR
VALUES (10,6);
INSERT INTO UTILISATEUR
VALUES (11,6);
INSERT INTO UTILISATEUR
VALUES (12,3);
INSERT INTO UTILISATEUR
VALUES (13,5);
INSERT INTO UTILISATEUR
VALUES (14,6);
INSERT INTO UTILISATEUR
VALUES (15,6);
INSERT INTO UTILISATEUR
VALUES (16,7);
INSERT INTO UTILISATEUR
VALUES (17,3);
INSERT INTO UTILISATEUR
VALUES (18,8);
INSERT INTO UTILISATEUR
VALUES (19,1);
INSERT INTO UTILISATEUR
VALUES (20,5);