CREATE UNIQUE INDEX besoin_client_pressing_id_pk
ON BESOIN_CLIENT_PRESSINGS (ID_BESOIN_CLIENT_PRESSING) ;


ALTER TABLE BESOIN_CLIENT_PRESSINGS
ADD ( CONSTRAINT     besoin_client_pressing_id_pk
                     PRIMARY KEY (ID_BESOIN_CLIENT_PRESSING));