ALTER TABLE SERVICES
ADD
(
    CONSTRAINT SERVICE_PK
    PRIMARY KEY (ID_SERVICE)
);

ALTER TABLE SERVICES
ADD 
CONSTRAINT FK_SERVICE
FOREIGN KEY (ID_SERVICE)
REFERENCES 
TYPESERVICES (ID_TYPESERVICE);