
ALTER TABLE CLIENTS
ADD ( CONSTRAINT client_pk
        	 PRIMARY KEY (ID_CLIENT) 
    ) ;


ALTER TABLE CLIENTS
   ADD constraint FK_CLIENTS_REFERENCE_PERSONNE 
            FOREIGN KEY (ID_PERSONNE)
                REFERENCES PERSONNES (ID_PERSONNE);