ALTER TABLE ADRESSES
   ADD constraint FK_ADRESSES_REFERENCE_BESOINSC foreign key (ID_BESOIN)
      REFERENCES BESOINSCLIENT (ID_BESOIN);

ALTER TABLE ADRESSES
   ADD constraint FK_ADRESSES_REFERENCE_PERSONNE foreign key (ID_PERSONNE)
      REFERENCES PERSONNES (ID_PERSONNE);