ALTER TABLE LINGECLIENT
   add CONSTRAINT FK_LINGECLI_REFERENCE_TYPELING 
            FOREIGN KEY (ID_TYPELINGE)
                REFERENCES TYPELINGE (ID_TYPELINGE);

ALTER TABLE LINGECLIENT
   add CONSTRAINT FK_LINGECLI_REFERENCE_BESOINSC 
            FOREIGN KEY (ID_BESOIN)
                REFERENCES BESOINSCLIENT (ID_BESOIN);