

ALTER TABLE OFFRES
   add CONSTRAINT FK_OFFRES_REFERENCE_SERVICES 
            FOREIGN KEY (ID_SERVICES)
                REFERENCES SERVICES (ID_SERVICES);

ALTER TABLE OFFRES
   add CONSTRAINT FK_OFFRES_REFERENCE_TYPELING 
            FOREIGN KEY (ID_TYPELINGE)
                REFERENCES TYPELINGE (ID_TYPELINGE);