alter table ROLES
  ADD constraint FK_ROLES_REFERENCE_PRESSING 
      FOREIGN KEY (ID_PRESSING)
            REFERENCES PRESSINGS (ID_PRESSING);

alter table ROLES
  ADD constraint FK_ROLES_REFERENCE_UTILISATEUR 
      FOREIGN KEY (ID_USER)
            REFERENCES UTILISATEUR (ID_USER);