
ALTER TABLE SERVICES
ADD 
CONSTRAINT FK_SERVICE_TYPESERVICE
FOREIGN KEY (ID_TYPESERVICE)
REFERENCES 
TYPESERVICES (ID_TYPESERVICE);

ALTER TABLE SERVICES
ADD 
CONSTRAINT FK_SERVICE_PRESSING
FOREIGN KEY (ID_PRESSING)
REFERENCES 
PRESSINGS (ID_PRESSING);
