
ALTER TABLE SERVICES
ADD 
CONSTRAINT FK_SERVICE
FOREIGN KEY (ID_TYPESERVICE)
REFERENCES 
TYPESERVICES (ID_TYPESERVICE);

ALTER TABLE SERVICES
ADD 
CONSTRAINT FK_SERVICE
FOREIGN KEY (ID_PRESSING)
REFERENCES 
TYPESERVICES (ID_PRESSING);
