ALTER TABLE VALEURATTRIBUTS
    ADD CONSTRAINT FK_VALEURATTRIBUTS_ATTRIBUT FOREIGN KEY (ID_ATTRIBUT)
        REFERENCES ATTRIBUTS (ID_ATTRIBUT);

-- ALTER TABLE VALEURATTRIBUTS
--     ADD CONSTRAINT FK_VALEURATTRIBUTS_OFFRE FOREIGN KEY (ID_TYPELINGE)
--         REFERENCES OFFRES (ID_TYPELINGE);