PROMPT *************** CREATE OFFRES TABLES ******************

CREATE TABLE IF NOT EXISTS OFFRES 
(
   ID_SERVICES          NUMBER(10),
   ID_TYPELINGE         NUMBER(10),
   NOM                  VARCHAR(255),
   DESCRIPTION          VARCHAR(255)                   
);


ALTER TABLE OFFRES
   add CONSTRAINT FK_OFFRES_REFERENCE_SERVICES 
            FOREIGN KEY (ID_SERVICES)
                REFERENCES SERVICES (ID_SERVICES);

ALTER TABLE OFFRES
   add CONSTRAINT FK_OFFRES_REFERENCE_TYPELING 
            FOREIGN KEY (ID_TYPELINGE)
                REFERENCES TYPELINGE (ID_TYPELINGE);
