PROMPT ****************** CREATE LINGE CLIENT TABLE ****************


CREATE TABLE IF NOT EXISTS LINGECLIENT 
(
   ID_TYPELINGE         NUMBER(10),
   ID_BESOIN            NUMBER(10),
   QUANTITE             NUMBER(10),
   IMAGE                varbinary(2000)
);



ALTER TABLE LINGECLIENT
   add CONSTRAINT FK_LINGECLI_REFERENCE_TYPELING 
            FOREIGN KEY (ID_TYPELINGE)
                REFERENCES TYPELINGE (ID_TYPELINGE);

ALTER TABLE LINGECLIENT
   add CONSTRAINT FK_LINGECLI_REFERENCE_BESOINSC 
            FOREIGN KEY (ID_BESOIN)
                REFERENCES BESOINSCLIENT (ID_BESOIN);