PROMPT ************ CREATE PERSONNESPHYSIQUE TABLE ***********

CREATE TABLE  PERSONNESPHYSIQUE 
(
   ID_PERSPHY           NUMBER(10),
   ID_PERSONNE          NUMBER(10),
   IMAGE                varbinary(2000),
   PRIMARY KEY (ID_PERSPHY)
);
