PROMPT ************ CREATE PERSONNESPHYSIQUE TABLE ***********

CREATE TABLE IF NOT EXISTS PERSONNESPHYSIQUE 
(
   ID_PERSPHY           NUMBER(10),
   ID_PERSONNE          NUMBER(10),
   IMAGE                varbinary(2000)
);


ALTER TABLE PERSONNESPHYSIQUE
ADD ( CONSTRAINT personnep_pk
        	 PRIMARY KEY (ID_PERSPHY) 
    );

ALTER TABLE PERSONNESPHYSIQUE
   add CONSTRAINT FK_PERSONP_REFERENCE_PERSON
            FOREIGN KEY (ID_PERSONNE)
                REFERENCES PERSONNES (ID_PERSONNE);