PROMPT ***************** CREATE VALEUR ATTRIBUT TABLE **************************

CREATE IF NOT EXISTS TABLE VALEURATTRIBUTS
(
    ID_ATTRIBUT          NUMBER(10),                  null,
    VALEUR               varchar(255)
);

ALTER TABLE VALEURATTRIBUTS
ADD
(
    CONSTRAINT VALEURATTIBUT_PK
    PRIMARY KEY (ID_ATTRIBUT)
);